INVALID_PAYLOAD_DATA_MESSAGE = 'Invalid Data'
INVALID_GATE_ID_MESSAGE = 'Invalid Gate ID'
INVALID_FORWARD_URL_MESSAGE = 'Invalid Forward URL'
INVALID_FILENAME_MESSAGE = 'Invalid Filename Image'
INVALID_DATA_IMAGE_MESSAGE = 'Invalid data image'
INVALID_TICKET_NUMBER_MESSAGE = 'Invalid ticket number'

OK_MESSAGE = 'OK'

ERROR_FORWARD_MESSAGE = 'an error has occurred. see log for details.'
FORWARD_SUCCESS_MESSAGE = 'data has been forwarded.'
REGISTER_SUCCESS = 'successfully registered data stream and gate id'
MESSAGE_REVOKE_GATE_ID_SUCCESS = 'service Gate ID has successfully been revoked'
MESSAGE_REVOKE_GATE_ID_FAILED = 'an error has occurred while revoking Gate ID'
MESSAGE_GATE_ID_NOT_FOUND = 'Data Gate ID does not exists.'
MESSAGE_TICKET_NUMBER_NOT_FOUND = 'Ticket Number Not Found'
