DEFAULT_STATE = "No Vehicle Detected"
DEFAULT_PORT = 8080
DEFAULT_DB_FILE = "data-state.sqlite3"
DEFAULT_LOG_NAME = "master-node.log"

HTTP_STATUS_OK = 200
HTTP_STATUS_BAD_REQUEST = 400
HTTP_STATUS_NOT_FOUND = 404
HTTP_STATUS_INTERNAL_SERVER_ERROR = 500

DEFAULT_DATETIME_FORMAT = "YYYY-MM-DD HH:mm:ss"
DEFAULT_MAX_LIMIT_RESET_STATE = 10  # in seconds
DEFAULT_RESET_STATE_SCHEDULER_TIME = 1  # in seconds